export const LOAD_APPLICATION = 'LOAD_APPLICATION';
export const LOAD_APPLICATION_SUCCESS = 'LOAD_APPLICATION_SUCCESS';
export const LOAD_APPLICATION_FAILURE = 'LOAD_APPLICATION_FAILURE';
export const SAVE_APPLICATION = 'SAVE_APPLICATION';
export const SAVE_APPLICATION_SUCCESS = 'SAVE_APPLICATION_SUCCESS';

export const LOAD_TECHNOLOGIES = 'LOAD_TECHNOLOGIES';
export const LOAD_TECHNOLOGIES_SUCCESS = 'LOAD_TECHNOLOGIES_SUCCESS';
export const LOAD_TECHNOLOGIES_FAILURE = 'LOAD_TECHNOLOGIES_FAILURE';

export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';

export const LOAD_CAPABILITIES = 'LOAD_CAPABILITIES';
export const LOAD_CAPABILITIES_SUCCESS = 'LOAD_CAPABILITIES_SUCCESS';
export const LOAD_CAPABILITIES_FAILURE = 'LOAD_CAPABILITIES_FAILURE';

export const LOAD_BUSINESS_POC = 'LOAD_BUSINESS_POC';
export const LOAD_BUSINESS_POC_SUCCESS = 'LOAD_BUSINESS_POC_SUCCESS';
export const LOAD_BUSINESS_POC_FAILURE = 'LOAD_BUSINESS_POC_FAILURE';

export const LOAD_TECH_POC = 'LOAD_TECH_POC';
export const LOAD_TECH_POC_SUCCESS = 'LOAD_TECH_POC_SUCCESS';
export const LOAD_TECH_POC_FAILURE = 'LOAD_TECH_POC_FAILURE';