export const LOAD_APPLICATION = 'LOAD_APPLICATION';
export const LOAD_APPLICATION_START = 'LOAD_APPLICATION_START';
export const LOAD_APPLICATION_SUCCESS = 'LOAD_APPLICATION_SUCCESS';
export const LOAD_APPLICATION_FAILURE = 'LOAD_APPLICATION_FAILURE';

export const SAVE_APPLICATION = 'SAVE_APPLICATION';
export const SAVE_APPLICATION_START = 'SAVE_APPLICATION_START';
export const SAVE_NEW_APPLICATION = 'SAVE_NEW_APPLICATION';
export const SAVE_APPLICATION_SUCCESS = 'SAVE_APPLICATION_SUCCESS';
export const SAVE_NEW_APPLICATION_FAILURE = 'SAVE_NEW_APPLICATION_FAILURE';

export const LOAD_TECHNOLOGIES = 'LOAD_TECHNOLOGIES';
export const UPDATE_TECHNOLOGIES = 'UPDATE_TECHNOLOGIES';
export const LOAD_TECHNOLOGIES_SUCCESS = 'LOAD_TECHNOLOGIES_SUCCESS';
export const LOAD_TECHNOLOGIES_FAILURE = 'LOAD_TECHNOLOGIES_FAILURE';

export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';

export const LOAD_CAPABILITIES = 'LOAD_CAPABILITIES';
export const UPDATE_CAPABILITIES = 'UPDATE_CAPABILITIES';
export const LOAD_CAPABILITIES_SUCCESS = 'LOAD_CAPABILITIES_SUCCESS';
export const LOAD_CAPABILITIES_FAILURE = 'LOAD_CAPABILITIES_FAILURE';

export const LOAD_POCS = 'LOAD_POCS';
export const UPDATE_POCS = 'UPDATE_POCS';
export const UPDATE_POC_SUCCESS = 'UPDATE_POC_SUCCESS';
export const LOAD_POCS_SUCCESS = 'LOAD_POCS_SUCCESS';
export const LOAD_POCS_FAILURE = 'LOAD_POCS_FAILURE';

export const LOAD_PLATFORMS = 'LOAD_PLATFORMS';
export const LOAD_PLATFORMS_SUCCESS = 'LOAD_PLATFORMS_SUCCESS';
export const LOAD_PLATFORMS_FAILURE = 'LOAD_PLATFORMS_FAILURE';

export const LOAD_PROVIDERS = 'LOAD_PROVIDERS';
export const LOAD_PROVIDERS_SUCCESS = 'LOAD_PROVIDERS_SUCCESS';
export const LOAD_PROVIDERS_FAILURE = 'LOAD_PROVIDERS_FAILURE';

export const LOAD_PARENTSYSTEMS = 'LOAD_PARENTSYSTEMS';
export const UPDATE_PARENTSYSTEMS = 'UPDATE_PARENTSYSTEMS';
export const LOAD_PARENTSYSTEMS_SUCCESS = 'LOAD_PARENTSYSTEMS_SUCCESS';
export const LOAD_PARENTSYSTEMS_FAILURE = 'LOAD_PARENTSYSTEMS_FAILURE';

export const LOAD_INVESTMENTS = 'LOAD_INVESTMENTS';
export const UPDATE_INVESTMENTS = 'UPDATE_INVESTMENTS';
export const LOAD_INVESTMENTS_SUCCESS = 'LOAD_INVESTMENTS_SUCCESS';
export const LOAD_INVESTMENTS_FAILURE = 'LOAD_INVESTMENTS_FAILURE';

export const LOAD_PORTFOLIOS = 'LOAD_PORTFOLIOS';
export const LOAD_PORTFOLIOS_SUCCESS = 'LOAD_PORTFOLIOS_SUCCESS';
export const LOAD_PORTFOLIOS_FAILURE = 'LOAD_PORTFOLIOS_FAILURE';

export const LOAD_FISMAS = 'LOAD_FISMAS';
export const UPDATE_FISMAS = 'UPDATE_FISMAS';
export const LOAD_FISMAS_SUCCESS = 'LOAD_FISMAS_SUCCESS';
export const LOAD_FISMAS_FAILURE = 'LOAD_FISMAS_FAILURE';

export const LOAD_USER_LOCATIONS = 'LOAD_USER_LOCATIONS';
export const LOAD_USER_LOCATIONS_SUCCESS = 'LOAD_USER_LOCATIONS_SUCCESS';
export const LOAD_USER_LOCATIONS_FAILURE = 'LOAD_USER_LOCATIONS_FAILURE';

export const DOES_EXIST = 'DOES_EXIST';
export const DOES_EXIST_INITIATE = 'DOES_EXIST_INITIATE';
export const DOES_EXIST_SUCCESS = 'DOES_EXIST_SUCCESS';
export const DOES_EXIST_FAILURE = 'DOES_EXIST_FAILURE';

export const LOAD_APPLICATION_GENERAL = 'LOAD_APPLICATION_GENERAL';
export const LOAD_APPLICATION_GENERAL_START = 'LOAD_APPLICATION_GENERAL_START';
export const LOAD_APPLICATION_GENERAL_SUCCESS = 'LOAD_APPLICATION_GENERAL_SUCCESS';
export const LOAD_APPLICATION_GENERAL_FAILURE = 'LOAD_APPLICATION_GENERAL_FAILURE';
export const SAVE_APPLICATION_GENERAL_FAILURE = 'SAVE__APPLICATION_GENERAL_FAILURE';
export const SAVE_APPLICATION_GENERAL_START = 'SAVE_APPLICATION_GENERAL_START';
export const SAVE_APPLICATION_GENERAL_SUCCESS = 'SAVE_APPLICATION_GENERAL_SUCCESS';

export const LOAD_APPLICATION_BUSINESS = 'LOAD_APPLICATION_BUSINESS';
export const LOAD_APPLICATION_BUSINESS_START = 'LOAD_APPLICATION_BUSINESS_START';
export const LOAD_APPLICATION_BUSINESS_SUCCESS = 'LOAD_APPLICATION_BUSINESS_SUCCESS';
export const LOAD_APPLICATION_BUSINESS_FAILURE= 'LOAD_APPLICATION_BUSINESS_FAILURE';
export const SAVE_APPLICATION_BUSINESS_FAILURE = 'SAVE__APPLICATION_BUSINESS_FAILURE';
export const SAVE_APPLICATION_BUSINESS_START = 'SAVE_APPLICATION_BUSINESS_START';
export const SAVE_APPLICATION_BUSINESS_SUCCESS = 'SAVE_APPLICATION_BUSINESS_SUCCESS';

export const LOAD_APPLICATION_TECHNOLOGY = 'LOAD_APPLICATION_TECHNOLOGY';
export const LOAD_APPLICATION_TECHNOLOGY_START = 'LOAD_APPLICATION_TECHNOLOGY_START';
export const LOAD_APPLICATION_TECHNOLOGY_SUCCESS = 'LOAD_APPLICATION_TECHNOLOGY_SUCCESS';
export const LOAD_APPLICATION_TECHNOLOGY_FAILURE = 'LOAD_APPLICATION_TECHNOLOGY_FAILURE';
export const SAVE_APPLICATION_TECHNOLOGY_FAILURE = 'SAVE__APPLICATITECHNOLOGY_FAILURE';
export const SAVE_APPLICATION_TECHNOLOGY_START = 'SAVE_APPLICATION_TECHNOLOGY_START';
export const SAVE_APPLICATION_TECHNOLOGY_SUCCESS = 'SAVE_APPLICATION_TECHNOLOGY_SUCCESS';
//Updating the state
export const UPDATE_FIELD_APP = 'UPDATE_FIELD_APP';

export const SAVE_APPLICATION_FAILED = 'SAVE_APPLICATION_FAILED';