export const LOAD_APPLICATION = 'LOAD_APPLICATION';
export const LOAD_APPLICATION_SUCCESS = 'LOAD_APPLICATION_SUCCESS';
export const LOAD_APPLICATION_FAILURE = 'LOAD_APPLICATION_FAILURE';
export const SAVE_APPLICATION = 'SAVE_APPLICATION';
export const SAVE_APPLICATION_SUCCESS = 'SAVE_APPLICATION_SUCCESS';

export const LOAD_TECHNOLOGIES = 'LOAD_TECHNOLOGIES';
export const LOAD_TECHNOLOGIES_SUCCESS = 'LOAD_TECHNOLOGIES_SUCCESS';
export const LOAD_TECHNOLOGIES_FAILURE = 'LOAD_TECHNOLOGIES_FAILURE';

export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';

export const LOAD_CAPABILITIES = 'LOAD_CAPABILITIES';
export const LOAD_CAPABILITIES_SUCCESS = 'LOAD_CAPABILITIES_SUCCESS';
export const LOAD_CAPABILITIES_FAILURE = 'LOAD_CAPABILITIES_FAILURE';

export const LOAD_BUSINESS_POC = 'LOAD_BUSINESS_POC';
export const LOAD_BUSINESS_POC_SUCCESS = 'LOAD_BUSINESS_POC_SUCCESS';
export const LOAD_BUSINESS_POC_FAILURE = 'LOAD_BUSINESS_POC_FAILURE';

export const LOAD_TECH_POC = 'LOAD_TECH_POC';
export const LOAD_TECH_POC_SUCCESS = 'LOAD_TECH_POC_SUCCESS';
export const LOAD_TECH_POC_FAILURE = 'LOAD_TECH_POC_FAILURE';

export const LOAD_PLATFORMS = 'LOAD_PLATFORMS';
export const LOAD_PLATFORMS_SUCCESS = 'LOAD_PLATFORMS_SUCCESS';
export const LOAD_PLATFORMS_FAILURE = 'LOAD_PLATFORMS_FAILURE';

export const LOAD_PROVIDERS = 'LOAD_PROVIDERS';
export const LOAD_PROVIDERS_SUCCESS = 'LOAD_PROVIDERS_SUCCESS';
export const LOAD_PROVIDERS_FAILURE = 'LOAD_PROVIDERS_FAILURE';

export const LOAD_PARENTSYSTEMS = 'LOAD_PARENTSYSTEMS';
export const LOAD_PARENTSYSTEMS_SUCCESS = 'LOAD_PARENTSYSTEMS_SUCCESS';
export const LOAD_PARENTSYSTEMS_FAILURE = 'LOAD_PARENTSYSTEMS_FAILURE';

export const LOAD_INVESTMENTS = 'LOAD_INVESTMENTS';
export const LOAD_INVESTMENTS_SUCCESS = 'LOAD_INVESTMENTS_SUCCESS';
export const LOAD_INVESTMENTS_FAILURE = 'LOAD_INVESTMENTS_FAILURE';

export const LOAD_PORTFOLIOS = 'LOAD_PORTFOLIOS';
export const LOAD_PORTFOLIOS_SUCCESS = 'LOAD_PORTFOLIOS_SUCCESS';
export const LOAD_PORTFOLIOS_FAILURE = 'LOAD_PORTFOLIOS_FAILURE';

export const LOAD_FISMAS = 'LOAD_FISMAS';
export const LOAD_FISMAS_SUCCESS = 'LOAD_FISMAS_SUCCESS';
export const LOAD_FISMAS_FAILURE = 'LOAD_FISMAS_FAILURE';